### ISSUE TITLE
Serverless configuration tasks

### ISSUE THREAD

**Issue by Danwhy** [TheScienceMuseum/360-image-uploader#11]
- [x] prefix all resources with 'smgco-''

- [x] tag all resources with 'System=CollectionsOnline' (if possible)

- [x] make uploaded S3 resources public

- [x] make forms/handlers private (@jamieu can setup an IP restricted IAM)

- [x] show error if no id or title (ideally on upload form, but if not just go to list and show error)

- [x] increase Lambda timeout from 6 secs

- [x] JSON feed of what's in bucket (id : path)

- [x] add `modification_date` to JSON feed

- [x] set individual IAM permissions per Resource

**Comment by Danwhy** [comment]
@jamieu This is what the JSON looks like:
```json
[{
	"title": "Teapot",
	"id": "1234-567",
	"path": "smgco-360/17aa8e0f-0897-4030-9de5-cf7b273d86dd",
	"active": true,
	"modification_date": "2018-07-20T14:29:17.873Z"
}, {
	"title": "'Maltese Cross' apparatus used to demonstrate Crooke's dark space",
	"id": "1995-786",
	"path": "smgco-360/8a45cc72-69ae-4566-807d-4dfa44eebed7",
	"active": true,
	"modification_date": "2018-07-20T14:22:44.360Z"
}]
```
We can still change it to however you/K-int want it though

**Comment by jamieu** [comment]
Perfect!
