### ISSUE TITLE
Extra fields to parse (if we have time)

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/360-image-uploader#12]
Focus on the existing issues as a priority. But if you get time / it's easy would be good to also parse out the `backgroundcolor` and `copyright` fields (both are optional fields)

We're not going to use the fields immediately, it's more covering off edge cases, so don't jeopardise getting the other more important issues resolved first. But if you have item and it's just a case of cut/pasting some extra fields in the serveless .yaml file it would be a nice to have.

Both fields are optional and most of the time will be empty.

- backgroundcolor="0x000000"
- copyright="© The Board of Trustees of the Science Museum" 

```
  <view>
    <start row="0" column="0" state="0"/>
    <zoom default="1.000" centerx="0.00000" centery="0.00000" min="1" max="2.000"/>
    <viewer imagescaling="1" backgroundcolor="0x000000" background="1"/>
  </view>
  <autorotate speed="1.000" delay="5.00" start="0"/>
  <userdata title="Model of the ‘Optimus’ water closet," datetime="" description="" copyright="© The Board of Trustees of the Science Museum" author="" source="" comment="" info="1961-32"/>
```

**Comment by tobystokes** [comment]
@jamie we discussed parsing out the `backgroundcolor` on the front end when we load the player. Assign to me if you want me to do it?
