### ISSUE TITLE
Authorisation

### ISSUE THREAD

**Issue by Danwhy** [TheScienceMuseum/360-image-uploader#6]
Currently we have the static html form publicly accessible.
When we have the image upload functionality, we will have to make sure this has some kind of authorisation to ensure that anybody cannot upload files.
A solution may be to make the file accessible only to the Science Museum internal network.

**Comment by jamieu** [comment]
Hi @Danwhy 

I'll see if I can setup an IAM user/policy that only allows access to the SMG network and a bucket policy file that only users with that IAM user/polic access to the **/admin** folder in that bucket.  

That way we can put all the upload/list pages in the **/admin** folder of that folder?

**How can I use IAM policies to grant user-specific access to specific folders?**
https://aws.amazon.com/premiumsupport/knowledge-center/iam-s3-user-specific-folder/

**AIM to allowing access to SMG IP range**
https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_aws_deny-ip.html

**Comment by jamieu** [comment]
Works well,

Although I do need to allow access to another server (EC2 owned by the same account) within AWS to read the JSON feed.

Wondering if it's best to just add another IP range/address or if there is a way of saying 'resources owned by this AWS account can access this endpoint'?
